---

- name: Registering known hosts
  known_hosts:
    host: "{{ item.name if item.name is defined else item }}"
    key: "{{ item.key if item.key is defined else lookup('pipe', 'ssh-keyscan -t rsa ' + item) }}"
    path: /etc/ssh/ssh_known_hosts
    state: present
  with_items: ssh_known_hosts
